### ISSUE TITLE
AssertionError in TrDesign_GD_demo Part 2 Step 2 in Jupyter notebook

### ISSUE THREAD

**Issue by spark157** [gjoni/trDesign#1]
Hello,

I am running TrDesign_GD_demo.ipynb on Linux (not in Colab) and in Part 2 Step 2 I get many warnings:

# WARNING, for demo we use n_models=1, in practice you should ALWAYS use n_models=5
model = mk_design_model(add_pdb=True, n_models=1)

mode: single sequence design
WARNING: Entity <bound method PSSM.call of <models.PSSM object at 0x2b5fa15e9b90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method PSSM.call of <models.PSSM object at 0x2b5fa15e9b90>>: AttributeError: module 'gast' has no attribute 'Num'
loading model: xaa
WARNING: Entity <bound method instance_norm.call of <models.instance_norm object at 0x2b5fa1648250>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method instance_norm.call of <models.instance_norm object at 0x2b5fa1648250>>: AssertionError: Bad argument number for Name: 3, expecting 4
...

The warnings do not appear if I run the notebook in Colab. Also, after the warnings the does still run and would appear to generate correct results. Just thought you might want to know.

Thanks!

Scott

**Comment by sokrypton** [comment]
Hi Scott,
Thanks for the report! What version of TensorFlow are you using?

**Comment by spark157** [comment]
Hi - I was just checking so I could add that info:

tensorflow-gpu==1.14.1
gast==0.3.3

A quick search perhaps my version of gast is an issue.

**Comment by sokrypton** [comment]
Yeah... it seems the new gast version does not like tensorflow v1. You can either upgrade to tensorflow 2... or downgrade gast to version 0.2.2.
`pip install --user gast==0.2.2`

**Comment by sokrypton** [comment]
Hi Scott, can you try run again (you'll need to download models.py again). I added more warning-suppressing code I found online. I hope that fixes it!

**Comment by spark157** [comment]
Hi,

Downloading models.py again didn't seem to fix the output however doing pip install gast==0.2.2 did. Hope that helps. Thanks.

Scott
