### ISSUE TITLE
< ERROR: Output file not defined --out=None >

### ISSUE THREAD

**Issue by johnnytam100** [gjoni/trDesign#3]
Hi, I tried to run by `python design.py -p 1QYS.pdb -o tmp.txt` but it appeared: 
< ERROR: Output file not defined --out=None >

**Comment by sokrypton** [comment]
Hmmmm... worked for me:
https://colab.research.google.com/drive/1Nm-4JHGBvI821wWcvJ976icqpcFLLDJT

What version of python are you using?

**Comment by johnnytam100** [comment]
Um... It worked in the notebook.
I was using python 3.7 but don't know why, I have tried both -o and --out.

**Comment by sokrypton** [comment]
When you say notebook are you referring to Google colab environment or your own jupyter environment?

**Comment by johnnytam100** [comment]
Sorry for the late reply.
I referred to the Google colab environment.
